FROM python:3.11-slim-bullseye

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
  && apt-get -y install libpq-dev gcc netcat \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /usr/src/app/
COPY requirements-dev.txt /usr/src/app/
RUN pip install --upgrade pip \
  && pip install -r requirements-dev.txt

COPY . /usr/src/app/

RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]