FROM python:3.11.2-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0
ENV SECRET_KEY brainag
ENV DJANGO_ALLOWED_HOSTS localhost 127.0.0.1 [::1]

RUN apt-get update \
  && apt-get -y install gcc postgresql \
  && apt-get clean

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN adduser --disabled-password myuser
USER myuser

CMD gunicorn brain_ag_teste.wsgi:application --bind 0.0.0.0:$PORT