version: '3.8'

services:
  brain-ag-teste:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
  brain-ag-teste-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=brainag
      - POSTGRES_PASSWORD=brainag
      - POSTGRES_DB=brainag_dev

volumes:
  postgres_data: